Resources:
  ProfilesTable:
    Type: AWS::DynamoDB::Table
    # DeletionPolicy: Retain # prevent resource from being deleted by CloudFormation
    Properties:
      TableName: ${self:provider.environment.PROFILES_TABLE}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST # auto-scale with on-demand capacity
