Resources:
  FilesS3BUCKET:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:provider.environment.FILES_S3_BUCKET}
      # set CORS policy
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: Policy
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadWriteBucketPolicy
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource: arn:aws:s3:::${self:provider.environment.FILES_S3_BUCKET}/*
      Bucket: !Ref FilesS3BUCKET
