service: udacity-capstone
app: udacity-serverless-blog

plugins:
  - serverless-bundle # package functions with Webpack
  - serverless-offline # offline testing
  - serverless-dotenv-plugin # load .env as environment variables
  - serverless-bundle # add es6/Typescript support see https://github.com/AnomalyInnovations/serverless-bundle

package:
  individually: true

# stage/region defaults set if not overridden when running serverless commands
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-2'}
  profile: serverless-marco

  environment:
    POSTS_TABLE: ${self:provider.stage}-posts

functions:
  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  CreatePost:
    handler: src/lambda/http/createPost.handler
    events:
      - http:
          path: /posts
          method: post
          cors: true
          authorizer: Auth
          request:
            schema:
              application/json: ${file(src/requestValidators/createPost.json)}

Resources:
  - ${file(src/resources/api-gateway-errors.yml)} # API Gateway errors
  - ${file(src/resources/dynamodb-table.yml)} # DynamoDB
  - ${file(src/resources/s3-bucket.yml)} # S3
  - ${file(src/resources/cognito-user-pool.yml)} # Cognito User Pool
  - ${file(src/resources/cognito-identity-pool.yml)} # Cognito Identity Pool
