service: udacity-capstone
app: udacity-serverless-blog

plugins:
  - serverless-bundle # package functions with Webpack
  - serverless-offline # offline testing
  - serverless-dotenv-plugin # load .env as environment variables
  - serverless-bundle # add es6/Typescript support see https://github.com/AnomalyInnovations/serverless-bundle

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-2'}
  profile: serverless-marco
