service: udacity-capstone
app: udacity-serverless-blog

plugins:
    # package functions with Webpack
  - serverless-bundle
     # offline testing
   - serverless-offline
     # load .env as environment variables
   - serverless-dotenv-plugin
     # add es6/Typescript support see https://github.com/AnomalyInnovations/serverless-bundle
   - serverless-bundle
     # testing
   - serverless-mocha

# referring to functions - gives more control for optimised deployments
package:
  individually: true

# stage/region defaults set if not overridden when running serverless commands
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-2'}
  profile: serverless-marco

  environment:
    POSTS_TABLE: ${self:provider.stage}-posts
    PROFILES_TABLE: ${self:provider.stage}-profiles

functions:
  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  CreatePost:
    handler: src/lambda/http/createPost.handler
    events:
      - http:
          path: /posts
          method: post
          cors: true
          authorizer: Auth
          request:
            schema:
              application/json: ${file(src/requestValidators/createPost.json)}

Resources:
    # API Gateway errors
  - ${file(src/resources/api-gateway-errors.yml)}
    # DynamoDB-Posts
  - ${file(src/resources/dynamodb-posts-table.yml)}
    # DynamoDB-Profiles
  - ${file(src/resources/dynamodb-profiles-table.yml)}
    # S3
  - ${file(src/resources/s3-bucket.yml)}
